import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";


export const metadata: Metadata = {
  title: "Nextjs Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        {children}

        <footer>footer</footer>
        </body>
    </html>
  );
}
